version: "2"
services:
  centos6.6:
    build:
      context: .
      dockerfile: dockerfile-centos6.6
    volumes:
      - ".:/var/lib/tomahawk"
    working_dir: /var/lib/tomahawk
    command: /bin/bash -c 'service sshd restart && pip install -e . && tomahawk -h localhost "echo あ"'
  ubuntu16.04:
    build:
      context: .
      dockerfile: dockerfile-ubuntu16.04
    volumes:
      - ".:/var/lib/tomahawk"
    working_dir: /var/lib/tomahawk
    command: /bin/bash -c 'service ssh restart && pip3 install -e . && tomahawk -h localhost "echo あ"'
